//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdebFacCollateral
    {
        public string FacId { get; set; }
        public int Seq { get; set; }
        public string DebtectorId { get; set; }
        public string DebtectorFacId { get; set; }
        public string JenisAgunanKet { get; set; }
        public Nullable<double> NilaiAgunanMenurutLJK { get; set; }
        public Nullable<double> ProsentaseParipasu { get; set; }
        public Nullable<System.DateTime> TanggalUpdate { get; set; }
        public string NomorAgunan { get; set; }
        public string JenisPengikatan { get; set; }
        public string JenisPengikatanKet { get; set; }
        public Nullable<System.DateTime> TanggalPengikatan { get; set; }
        public string NamaPemilikAgunan { get; set; }
        public string AlamatAgunan { get; set; }
        public string LokasiAgunan { get; set; }
        public string LokasiAgunanKet { get; set; }
        public Nullable<System.DateTime> TglPenilaianLjk { get; set; }
        public string PeringkatAgunan { get; set; }
        public string LembagaPemeringkat { get; set; }
        public string LembagaPemeringkatKet { get; set; }
        public string BuktiKepemilikan { get; set; }
        public Nullable<double> NilaiAgunanNjop { get; set; }
        public Nullable<double> NilaiAgunanIndep { get; set; }
        public string NamaPenilaiIndep { get; set; }
        public string Asuransi { get; set; }
        public Nullable<System.DateTime> TanggalPenilaianPenilaiIndependen { get; set; }
        public string Keterangan { get; set; }
    
        public virtual IdebFac IdebFac { get; set; }
    }
}
