//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppBureauReq
    {
        public string ReqId { get; set; }
        public string AppId { get; set; }
        public Nullable<int> Seq { get; set; }
        public string DatTypeCd { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string IDType { get; set; }
        public string IDNumber { get; set; }
        public string Gender { get; set; }
        public string Npwp { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string Addr3 { get; set; }
        public string CityName { get; set; }
        public string PostalCode { get; set; }
        public string ReqBy { get; set; }
        public Nullable<System.DateTime> ReqTime { get; set; }
        public string ReqType { get; set; }
    }
}
