//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustJob
    {
        public string AppId { get; set; }
        public int Seq { get; set; }
        public string CompName { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string Addr3 { get; set; }
        public string DistrictCd { get; set; }
        public string DistrictName { get; set; }
        public string SubDistrictCd { get; set; }
        public string SubDistrictName { get; set; }
        public string CityCd { get; set; }
        public string CityName { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNo { get; set; }
        public string PhoneExt { get; set; }
        public string PhoneStaCd { get; set; }
        public string Phone2No { get; set; }
        public string Phone2Ext { get; set; }
        public string Phone2StaCd { get; set; }
        public Nullable<bool> HomeAddrEqOffAddr { get; set; }
        public string PositionCd { get; set; }
        public string Position { get; set; }
        public string NOB { get; set; }
        public string Department { get; set; }
        public string EmployeeIDNo { get; set; }
        public string JobStatus { get; set; }
        public Nullable<int> CurrLojYY { get; set; }
        public Nullable<int> CurrLojMM { get; set; }
        public Nullable<int> TotalLojYY { get; set; }
        public Nullable<int> TotalLojMM { get; set; }
        public Nullable<int> PrevLojYY { get; set; }
        public Nullable<int> PrevLojMM { get; set; }
        public string PervCompName { get; set; }
        public string PrevPhoneNo { get; set; }
        public string PrevPhoneExt { get; set; }
        public Nullable<int> NoOfEmployee { get; set; }
        public string EwssResult { get; set; }
        public string RelPartyResult { get; set; }
        public string WellEstablishCompType { get; set; }
        public string ChangeToNewOffAddr { get; set; }
    }
}
