//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthGroup
    {
        public string GroupId { get; set; }
        public string GroupName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string RegBy { get; set; }
        public Nullable<System.DateTime> ApprvDate { get; set; }
        public string ApprvBy { get; set; }
        public Nullable<bool> IsDormant { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
