//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataImportLogDetail
    {
        public string BatchFileName { get; set; }
        public int RowNumber { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string KeyValue { get; set; }
        public string LogType { get; set; }
        public string LogMessage { get; set; }
    }
}
