//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataImportFlatFileColumn
    {
        public int ImportId { get; set; }
        public int Seq { get; set; }
        public string Name { get; set; }
        public Nullable<int> InputColumnWidth { get; set; }
        public Nullable<int> DataPrecision { get; set; }
        public Nullable<int> DataScale { get; set; }
        public string DataType { get; set; }
        public Nullable<int> OutputColumnWidth { get; set; }
        public Nullable<bool> TextQualified { get; set; }
    }
}
