//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppFlag
    {
        public string AppId { get; set; }
        public string BankCd { get; set; }
        public Nullable<double> DBSLnLimit_OS { get; set; }
        public string VerBillAddrMatch { get; set; }
        public string VerMobilePhnMatch { get; set; }
        public string NpwpDocFlag { get; set; }
        public string AMLRiskRating { get; set; }
        public string BureauType { get; set; }
    }
}
