//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataImportLog
    {
        public string BatchFileName { get; set; }
        public Nullable<int> TotalRow { get; set; }
        public Nullable<int> NoOfSuccess { get; set; }
        public Nullable<int> NoOfFailed { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
    }
}
