//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustPersonal
    {
        public string AppId { get; set; }
        public string CustNo { get; set; }
        public string CustName { get; set; }
        public string CustNameOnID { get; set; }
        public string CustNickName { get; set; }
        public string CustNameInCard { get; set; }
        public string NationalityCd { get; set; }
        public string MothersMaidenName { get; set; }
        public string GenderCd { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string IDTypeCd { get; set; }
        public string IdCardTrackCd { get; set; }
        public string IDNumber { get; set; }
        public string EduCd { get; set; }
        public string MaritalCd { get; set; }
        public Nullable<int> NoOfDependents { get; set; }
        public string HomeAddr1 { get; set; }
        public string HomeAddr2 { get; set; }
        public string HomeAddr3 { get; set; }
        public string HomeDistrictCd { get; set; }
        public string HomeDistrictName { get; set; }
        public string HomeSubDistrictCd { get; set; }
        public string HomeSubDistrictName { get; set; }
        public string HomeCityName { get; set; }
        public string HomePostalCode { get; set; }
        public string HomePhoneNo { get; set; }
        public string HomePhoneStaCd { get; set; }
        public Nullable<bool> HomeAddrEqIDAddr { get; set; }
        public string IDAddr1 { get; set; }
        public string IDAddr2 { get; set; }
        public string IDAddr3 { get; set; }
        public string IDDistrictCd { get; set; }
        public string IDDistrictName { get; set; }
        public string IDSubDistrictCd { get; set; }
        public string IDSubDistrictName { get; set; }
        public string IDCityName { get; set; }
        public string IDPostalCode { get; set; }
        public string PixelCode { get; set; }
        public string PixelAddr { get; set; }
        public string PixelWKCCode { get; set; }
        public string MobilePhoneNo { get; set; }
        public string MobilePhoneNo2 { get; set; }
        public string ExMobilePhone { get; set; }
        public string ResStaCd { get; set; }
        public Nullable<int> ResLOSYY { get; set; }
        public Nullable<int> ResLOSMM { get; set; }
        public string Npwp { get; set; }
        public string MailingAddrCd { get; set; }
        public string Email { get; set; }
        public string ChangeToNewHomeAddr { get; set; }
        public string CountryCd { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public string InsertBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
    }
}
