//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataImportDestColumn
    {
        public int ImportId { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string SourceColumnName { get; set; }
        public Nullable<bool> IsKey { get; set; }
        public string AutoFormula { get; set; }
    }
}
