//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdebFac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IdebFac()
        {
            this.IdebFacCollaterals = new HashSet<IdebFacCollateral>();
            this.IdebFacCollects = new HashSet<IdebFacCollect>();
            this.IdebFacPenjamins = new HashSet<IdebFacPenjamin>();
        }
    
        public string FacId { get; set; }
        public string IdebId { get; set; }
        public Nullable<int> Seq { get; set; }
        public string DebtectorId { get; set; }
        public string FacCat { get; set; }
    
        public virtual Ideb Ideb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdebFacCollateral> IdebFacCollaterals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdebFacCollect> IdebFacCollects { get; set; }
        public virtual IdebFacCredit IdebFacCredit { get; set; }
        public virtual IdebFacLc IdebFacLc { get; set; }
        public virtual IdebFacOther IdebFacOther { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdebFacPenjamin> IdebFacPenjamins { get; set; }
        public virtual IdebFacSb IdebFacSb { get; set; }
    }
}
