//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class App
    {
        public string AppId { get; set; }
        public string DataSource { get; set; }
        public string BranchId { get; set; }
        public string SourceCd { get; set; }
        public string CampaignCd { get; set; }
        public string LoanCentreCd { get; set; }
        public string AgentCd { get; set; }
        public string SalesCd { get; set; }
        public string MgmCd { get; set; }
        public string Org { get; set; }
        public string Type { get; set; }
        public string OriginAppId { get; set; }
        public string AppRefNo { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string SolicitationId { get; set; }
        public string VIPIndicator { get; set; }
        public string UseCreditDesired { get; set; }
        public string ProcCradleToGrave { get; set; }
        public string CreateCustRecord { get; set; }
        public string CreateRelRecord { get; set; }
        public string RelCd { get; set; }
        public string CreateBaseSegRecord { get; set; }
        public string SameCust { get; set; }
        public string EmbMethodCd { get; set; }
        public string BaseSegCd { get; set; }
        public string CardSchemeCd { get; set; }
        public string LoanPlanNo { get; set; }
        public string PrimaryAcc { get; set; }
        public string LoanRefNo { get; set; }
        public string RelTypeIndCd { get; set; }
        public string ProcessTypeCd { get; set; }
        public string AlgoProxyIncTest { get; set; }
        public string AlgoSegTest { get; set; }
        public string AlgoScoreTest { get; set; }
        public string AlgoTestTrack { get; set; }
        public string PLNameOfBank { get; set; }
        public string CustConsent { get; set; }
        public string MarcomConsent { get; set; }
        public string UpfrontReject { get; set; }
        public string ExcludeIndustry { get; set; }
        public Nullable<double> PLOptDBSMUE { get; set; }
        public Nullable<double> CCOptDBSMUE { get; set; }
        public Nullable<double> MLOptDBSMUE { get; set; }
        public Nullable<System.DateTime> SignatureDate { get; set; }
        public Nullable<int> AreaScore { get; set; }
        public string PSCd { get; set; }
        public string CustType { get; set; }
        public string TopupType { get; set; }
        public string OldestMOB { get; set; }
        public string OriginAccNo { get; set; }
        public string DiscFlag { get; set; }
        public string PINPIDPI2Flag { get; set; }
        public string RelWithBanks { get; set; }
        public string NeedProbing { get; set; }
        public string ProbingDetail { get; set; }
        public string ProbingDetail2 { get; set; }
        public Nullable<int> TotalCardIssuers { get; set; }
        public string BillPmtReg { get; set; }
        public string SavingAccNo { get; set; }
        public string ReqPrintBilling { get; set; }
        public string DocType { get; set; }
        public string Oth1 { get; set; }
        public string Oth2 { get; set; }
        public string Oth3 { get; set; }
        public string Oth4 { get; set; }
        public string Oth5 { get; set; }
        public string BatchFileName { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public string InsertBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
    }
}
