//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppBillPmt
    {
        public string AppId { get; set; }
        public int Seq { get; set; }
        public string BillerName { get; set; }
        public string BillAccNo { get; set; }
        public string NameOnBill { get; set; }
    }
}
