//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDecResp
    {
        public string AppId { get; set; }
        public Nullable<System.DateTime> GenTime { get; set; }
        public string Org { get; set; }
        public string Type { get; set; }
        public string Sage { get; set; }
        public string OriginAppId { get; set; }
        public string EwssResult { get; set; }
        public string LoanCode { get; set; }
        public string SLIKResultCheck { get; set; }
        public string SLIKID { get; set; }
        public Nullable<double> IncomeVer { get; set; }
        public Nullable<double> IncomeFinal { get; set; }
        public string ProxyIncMOB { get; set; }
        public string ProxyIncIssuer { get; set; }
        public Nullable<double> ProxyIncLimit { get; set; }
        public string OutsideMUE { get; set; }
        public Nullable<double> MultiCusLevelMUE { get; set; }
        public Nullable<double> TotalCCLimitOthBank { get; set; }
        public string SLIKResult { get; set; }
        public string SubDecCd { get; set; }
        public Nullable<int> NoOfNewULL12M { get; set; }
        public Nullable<double> TotActiveCCOS { get; set; }
        public Nullable<double> TotActiveCCLimit { get; set; }
        public Nullable<double> GrossOSOrLimit { get; set; }
        public Nullable<int> NoOfActiveCC { get; set; }
        public Nullable<int> WorstDPDl12M { get; set; }
        public Nullable<int> NoOfActiveHL { get; set; }
        public Nullable<int> NoOfActiveRev { get; set; }
        public Nullable<double> RatioOfRevOver90Pct { get; set; }
        public Nullable<int> NoOfUL { get; set; }
        public Nullable<int> NoOfSL { get; set; }
        public Nullable<int> OldestMOBAllFac { get; set; }
        public Nullable<int> LatestDeqMonth { get; set; }
        public Nullable<int> OldestMOBULCC { get; set; }
        public string PINPIDPI2Flag { get; set; }
        public string AKKIResult { get; set; }
        public string RatingResult { get; set; }
        public string BureauResult { get; set; }
        public Nullable<System.DateTime> RatingOpenDate { get; set; }
        public Nullable<double> RatingLimit { get; set; }
        public Nullable<double> RatingOSBal { get; set; }
        public string RatingPmtType { get; set; }
        public string RatingHistL12M { get; set; }
        public string RatingCardType { get; set; }
        public string RatingLatesSta { get; set; }
        public string BureauRatioCCODWithHL90Util { get; set; }
        public string BureauLatesMDelqGT0 { get; set; }
        public Nullable<int> BureauTotMOBCC { get; set; }
        public Nullable<double> BureauURActiveCCOSLimit { get; set; }
        public Nullable<int> BureauNoOfLoanOpenL18M { get; set; }
        public Nullable<System.DateTime> BureauDateLastCCTaken { get; set; }
        public Nullable<int> BureauMOBLastCCTaken { get; set; }
        public Nullable<int> BureauWorstDPDL6M { get; set; }
        public string BureauProfiling { get; set; }
        public string NeedProbing { get; set; }
        public string ProbingDetail { get; set; }
        public string ProbingDetail2 { get; set; }
        public string FieldHRArea { get; set; }
        public string TotalCCIssuers { get; set; }
        public Nullable<double> GrossAmtAggrCard { get; set; }
        public string ApproveDeclineCode { get; set; }
        public string Oth2 { get; set; }
        public Nullable<double> Dbr { get; set; }
        public Nullable<double> Dsr { get; set; }
        public Nullable<double> UtilizationRate { get; set; }
        public string PhoneSeg { get; set; }
    }
}
