//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppExLoan
    {
        public string AppId { get; set; }
        public int Seq { get; set; }
        public string DataTypeCd { get; set; }
        public string RelId { get; set; }
        public string LnTypeCd { get; set; }
        public string BankId { get; set; }
        public Nullable<double> Limit { get; set; }
        public Nullable<double> Outstanding { get; set; }
        public string LnAccNo { get; set; }
        public Nullable<double> Instalment { get; set; }
    }
}
