//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppFac
    {
        public string AppId { get; set; }
        public int Seq { get; set; }
        public string ProjectCd { get; set; }
        public string ProdTypeCd { get; set; }
        public string ProgTypeCd { get; set; }
        public string ProgramCd { get; set; }
        public Nullable<double> LimitReqAmt { get; set; }
        public string LoanCode { get; set; }
        public Nullable<int> Tenure { get; set; }
        public string LoanPurpCd { get; set; }
        public string LoanPurpOth { get; set; }
        public string AccBeneficiaryName { get; set; }
        public string AccBankName { get; set; }
        public string AccBankId { get; set; }
        public string AccBranchId { get; set; }
        public string AccNo { get; set; }
        public string BranchAreaExp1 { get; set; }
        public string PayeeName2 { get; set; }
        public string PayeeAccNo2 { get; set; }
        public string BranchAreaExp2 { get; set; }
        public string PayeeName3 { get; set; }
        public string PayeeAccNo3 { get; set; }
        public string BranchAreaExp3 { get; set; }
        public string DisbFeeFlag { get; set; }
        public Nullable<double> DisbPercentage1 { get; set; }
        public Nullable<double> DisbPercentage2 { get; set; }
        public Nullable<double> DisbPercentage3 { get; set; }
        public Nullable<double> DisbFixAmt1 { get; set; }
        public Nullable<double> DisbFixAmt2 { get; set; }
        public Nullable<double> DisbFixAmt3 { get; set; }
        public Nullable<double> PrevTopupLimit { get; set; }
        public string CardType { get; set; }
        public string PCTID { get; set; }
        public string FundTrans { get; set; }
        public double FundTransLnAmtReq { get; set; }
        public Nullable<int> FundTransLnTenureReq { get; set; }
        public string FundTransLnPmtType { get; set; }
        public string DDNomType { get; set; }
        public string DDPmtType { get; set; }
        public Nullable<int> DDReqDays { get; set; }
        public string PrevLnSegBaseCd { get; set; }
        public string TopUpSegCd { get; set; }
        public string InsProdCd { get; set; }
        public string ApprvDecCd { get; set; }
        public string SubDecCd { get; set; }
    }
}
