//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthUserFlag
    {
        public string UserId { get; set; }
        public Nullable<bool> IsLogon { get; set; }
        public Nullable<bool> IsRevoke { get; set; }
        public Nullable<int> FalsePwd { get; set; }
        public Nullable<System.DateTime> LastLogon { get; set; }
        public string LastHost { get; set; }
        public Nullable<System.DateTime> LastActivity { get; set; }
        public string TokenId { get; set; }
    }
}
