//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthUser
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string NIP { get; set; }
        public string ExtensionNo { get; set; }
        public string HomePhoneNo { get; set; }
        public string MobilePhoneNo { get; set; }
        public string UplinerId { get; set; }
        public Nullable<System.DateTime> PwdExpDate { get; set; }
        public string BranchId { get; set; }
        public string Position { get; set; }
        public string Departement { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string RegBy { get; set; }
        public Nullable<System.DateTime> ApprvDate { get; set; }
        public string ApprvBy { get; set; }
        public Nullable<int> LevelId { get; set; }
        public Nullable<bool> IsDormant { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
