//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustRel
    {
        public string RelId { get; set; }
        public string AppId { get; set; }
        public int Seq { get; set; }
        public string DataTypeCd { get; set; }
        public string RelTypeCd { get; set; }
        public string FullName { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string Addr3 { get; set; }
        public string DistrictCd { get; set; }
        public string DistrictName { get; set; }
        public string SubDistrictCd { get; set; }
        public string SubDistrictName { get; set; }
        public string CityCd { get; set; }
        public string CityName { get; set; }
        public string PostalCode { get; set; }
        public string HomePhoneNo { get; set; }
        public string HomePhoneStaCd { get; set; }
        public string MobilePhoneNo { get; set; }
        public string OtherPhoneNo { get; set; }
    }
}
