//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustFin
    {
        public string AppId { get; set; }
        public string IncDocType { get; set; }
        public Nullable<double> IncDeclare12M { get; set; }
        public Nullable<double> IncDeclareExtraYearly { get; set; }
        public Nullable<double> IncMonthlyBasedOnDoc { get; set; }
        public Nullable<double> IncMultiplier { get; set; }
        public Nullable<double> IncTotalBasedOnDoc { get; set; }
    }
}
