//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataImportFlatFile
    {
        public int ImportId { get; set; }
        public string SourceFileName { get; set; }
        public string SourceFilePath { get; set; }
        public string Format { get; set; }
        public string TextQualifier { get; set; }
        public string HeaderRowDelimiter { get; set; }
        public Nullable<int> HeaderRowsToSkip { get; set; }
        public Nullable<bool> ColumnNameIn1st { get; set; }
        public Nullable<int> DataRowsToSkip { get; set; }
        public string RowDelimiter { get; set; }
        public string ColumnDelimiter { get; set; }
        public Nullable<int> FtpId { get; set; }
    }
}
