//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRAMEWORK_FOREIGNKEY
    {
        public string TableName { get; set; }
        public string TableName_As { get; set; }
        public string TableName_FK { get; set; }
        public string Constraint_SQL { get; set; }
        public string TableName_Join { get; set; }
    }
}
