//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRAMEWORK_FORMULAFIELD
    {
        public string FieldId { get; set; }
        public string FieldCaption { get; set; }
        public string FieldDesc { get; set; }
        public string FieldFW { get; set; }
        public string FieldReff { get; set; }
        public string FormatString { get; set; }
        public string FilterType { get; set; }
        public string SETID { get; set; }
    }
}
