//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdebFacSb
    {
        public string FacId { get; set; }
        public string Ljk { get; set; }
        public string LjkKet { get; set; }
        public string Cabang { get; set; }
        public string CabangKet { get; set; }
        public Nullable<double> NominalSb { get; set; }
        public Nullable<System.DateTime> TanggalDibentuk { get; set; }
        public Nullable<System.DateTime> TanggalUpdate { get; set; }
        public Nullable<int> Bulan { get; set; }
        public Nullable<int> Tahun { get; set; }
        public string NoSuratBeharga { get; set; }
        public string JenisSuratBeharga { get; set; }
        public string JenisSuratBehargaKet { get; set; }
        public Nullable<double> SovereignRate { get; set; }
        public string Listing { get; set; }
        public string PeringkatSuratBeharga { get; set; }
        public string TujuanKepemilikan { get; set; }
        public string TujuanKepemilikanKet { get; set; }
        public Nullable<System.DateTime> TanggalDiterbitkan { get; set; }
        public Nullable<System.DateTime> TanggalJatuhTempo { get; set; }
        public Nullable<double> SukuBunga { get; set; }
        public string Valuta { get; set; }
        public string Kolektibilitas { get; set; }
        public Nullable<int> JumlahHariTunggakan { get; set; }
        public Nullable<double> NilaiDalamMataUangAsal { get; set; }
        public Nullable<double> NilaiPasar { get; set; }
        public Nullable<double> NilaiPerolehan { get; set; }
        public Nullable<double> Tunggakan { get; set; }
        public string SebabMacet { get; set; }
        public string SebabMacetKet { get; set; }
        public Nullable<System.DateTime> TanggalMacet { get; set; }
        public string Kondisi { get; set; }
        public string KondisiKet { get; set; }
        public Nullable<System.DateTime> TanggalKondisi { get; set; }
        public string Keterangan { get; set; }
    
        public virtual IdebFac IdebFac { get; set; }
    }
}
