//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdebIndivData
    {
        public string IdebId { get; set; }
        public int Seq { get; set; }
        public string DebtectorId { get; set; }
        public string NamaDebitur { get; set; }
        public string Identitas { get; set; }
        public string NoIdentitas { get; set; }
        public string JenisKelamin { get; set; }
        public string JenisKelaminKet { get; set; }
        public string Npwp { get; set; }
        public string TempatLahir { get; set; }
        public Nullable<System.DateTime> TanggalLahir { get; set; }
        public string Pelapor { get; set; }
        public string PelaporKet { get; set; }
        public Nullable<System.DateTime> TanggalDibentuk { get; set; }
        public Nullable<System.DateTime> TanggalUpdate { get; set; }
        public string Alamat { get; set; }
        public string Kelurahan { get; set; }
        public string Kecamatan { get; set; }
        public string KabKota { get; set; }
        public string KabKotaKet { get; set; }
        public string KodePos { get; set; }
        public string Negara { get; set; }
        public string NegaraKet { get; set; }
        public string Pekerjaan { get; set; }
        public string PekerjaanKet { get; set; }
        public string TempatBekerja { get; set; }
        public string BidangUsaha { get; set; }
        public string BidangUsahaKet { get; set; }
        public string KodeGelarDebitur { get; set; }
        public string StatusGelarDebitur { get; set; }
    
        public virtual Ideb Ideb { get; set; }
    }
}
