//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdebFacSummary
    {
        public string IdebId { get; set; }
        public Nullable<double> PlafonEfektifKredit { get; set; }
        public Nullable<double> PlafonEfektifLc { get; set; }
        public Nullable<double> PlafonEfektifBg { get; set; }
        public Nullable<double> plafonEfektifSec { get; set; }
        public Nullable<double> PlafonEfektifLainnya { get; set; }
        public Nullable<double> PlafonEfektifTotal { get; set; }
        public Nullable<double> BakiDebetKredit { get; set; }
        public Nullable<double> BakiDebetLc { get; set; }
        public Nullable<double> BakiDebetBg { get; set; }
        public Nullable<double> BakiDebetSec { get; set; }
        public Nullable<double> BakiDebetLainnya { get; set; }
        public Nullable<double> BakiDebetTotal { get; set; }
        public Nullable<int> KrediturBankUmum { get; set; }
        public Nullable<int> KrediturBPR_S { get; set; }
        public Nullable<int> KrediturLp { get; set; }
        public Nullable<int> KrediturLainnya { get; set; }
        public string KolekTerburuk { get; set; }
        public Nullable<int> KolekDataTerburuk { get; set; }
        public string KolekBulanDataTerburuk { get; set; }
        public Nullable<System.DateTime> KolekDataTerburukDate { get; set; }
    
        public virtual Ideb Ideb { get; set; }
    }
}
