//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdebCorpData
    {
        public string IdebId { get; set; }
        public int Seq { get; set; }
        public string DebtectorId { get; set; }
        public string NamaDebitur { get; set; }
        public string NamaLengkap { get; set; }
        public string Npwp { get; set; }
        public string BentukBu { get; set; }
        public string BentukBuKet { get; set; }
        public string GoPublic { get; set; }
        public string TempatPendirian { get; set; }
        public string NoAktaPendirian { get; set; }
        public Nullable<System.DateTime> TglAktaPendirian { get; set; }
        public string Pelapor { get; set; }
        public string PelaporKet { get; set; }
        public Nullable<System.DateTime> TanggalDibentuk { get; set; }
        public Nullable<System.DateTime> TanggalUpdate { get; set; }
        public string Alamat { get; set; }
        public string Kelurahan { get; set; }
        public string Kecamatan { get; set; }
        public string KabKota { get; set; }
        public string KabKotaKet { get; set; }
        public string KodePos { get; set; }
        public string Negara { get; set; }
        public string NegaraKet { get; set; }
        public string NoAktaTerakhir { get; set; }
        public Nullable<System.DateTime> TglAktaTerakhir { get; set; }
        public string SektorEkonomi { get; set; }
        public string SektorEkonomiKet { get; set; }
        public string Pemeringkat { get; set; }
        public string PemeringkatKet { get; set; }
        public string Peringkat { get; set; }
        public Nullable<System.DateTime> TanggalPemeringkatan { get; set; }
    
        public virtual Ideb Ideb { get; set; }
    }
}
