//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdebIndivSearchVar
    {
        public string IdebId { get; set; }
        public string NamaDebitur { get; set; }
        public string JenisKelamin { get; set; }
        public string JenisKelaminKet { get; set; }
        public string NoIdentitas { get; set; }
        public string Npwp { get; set; }
        public string TempatLahir { get; set; }
        public Nullable<System.DateTime> TanggalLahir { get; set; }
    
        public virtual Ideb Ideb { get; set; }
    }
}
