//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdebFacPenjamin
    {
        public string FacId { get; set; }
        public int Seq { get; set; }
        public string NamaPenjamin { get; set; }
        public string NomorIdentitas { get; set; }
        public Nullable<System.DateTime> TanggalUpdate { get; set; }
        public Nullable<System.DateTime> TanggalBuat { get; set; }
        public string JenisPenjamin { get; set; }
        public string JenisPenjaminKet { get; set; }
        public string AlamatPenjamin { get; set; }
        public string Keterangan { get; set; }
    
        public virtual IdebFac IdebFac { get; set; }
    }
}
