//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterSystemField
    {
        public string TableNM { get; set; }
        public Nullable<int> FieldPos { get; set; }
        public string FieldNM { get; set; }
        public string FieldTYPE { get; set; }
        public string FieldDesc { get; set; }
        public string FieldReff { get; set; }
        public string FieldAuto { get; set; }
        public Nullable<bool> FieldKey { get; set; }
        public Nullable<bool> FieldMan { get; set; }
        public Nullable<bool> GroupBy { get; set; }
        public Nullable<int> SortSeq { get; set; }
        public Nullable<bool> SortAsc { get; set; }
        public string AutoPrefix { get; set; }
        public string AutoSufix { get; set; }
        public string FormulaType { get; set; }
        public Nullable<bool> Locked { get; set; }
    }
}
