//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterSystem_AuditTrailDetail
    {
        public System.Guid TemporaryID { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
        public string FieldValueBefore { get; set; }
    
        public virtual ParameterSystem_AuditTrail ParameterSystem_AuditTrail { get; set; }
    }
}
