//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcGenAppId
    {
        public string Org { get; set; }
        public System.DateTime ProcDate { get; set; }
        public Nullable<bool> ProcFlag { get; set; }
        public Nullable<int> RunNo { get; set; }
    }
}
