//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdebFacCredit
    {
        public string FacId { get; set; }
        public string Ljk { get; set; }
        public string LjkKet { get; set; }
        public string Cabang { get; set; }
        public string CabangKet { get; set; }
        public Nullable<double> BakiDebet { get; set; }
        public Nullable<System.DateTime> TanggalDibentuk { get; set; }
        public Nullable<System.DateTime> TanggalUpdate { get; set; }
        public Nullable<int> Bulan { get; set; }
        public Nullable<int> Tahun { get; set; }
        public string SifatKredit { get; set; }
        public string SifatKreditKet { get; set; }
        public string JenisKredit { get; set; }
        public string JenisKreditKet { get; set; }
        public string AkadPembiayaan { get; set; }
        public string AkadPembiayaanKet { get; set; }
        public string NoRekening { get; set; }
        public Nullable<bool> BaruPerpanjangan { get; set; }
        public string NoAkadAwal { get; set; }
        public Nullable<System.DateTime> TanggalAkadAwal { get; set; }
        public string NoAkadAkhir { get; set; }
        public Nullable<System.DateTime> TanggalAkadAkhir { get; set; }
        public Nullable<System.DateTime> TanggalAwalKredit { get; set; }
        public Nullable<System.DateTime> TanggalMulai { get; set; }
        public Nullable<System.DateTime> TanggalJatuhTempo { get; set; }
        public string KategoriDebiturKode { get; set; }
        public string KategoriDebiturKet { get; set; }
        public string JenisPenggunaan { get; set; }
        public string JenisPenggunaanKet { get; set; }
        public string SektorEkonomi { get; set; }
        public string SektorEkonomiKet { get; set; }
        public string KreditProgramPemerintah { get; set; }
        public string KreditProgramPemerintahKet { get; set; }
        public string LokasiProyek { get; set; }
        public string LokasiProyekKet { get; set; }
        public string Valuta { get; set; }
        public Nullable<double> SukuBunga { get; set; }
        public string JenisSukuBunga { get; set; }
        public string JenisSukuBungaKet { get; set; }
        public string Kolektibilitas { get; set; }
        public Nullable<int> JumlahHariTunggakan { get; set; }
        public Nullable<double> NilaiProyek { get; set; }
        public Nullable<double> PlafonAwal { get; set; }
        public Nullable<double> Plafon { get; set; }
        public Nullable<double> RealisasiBulanBerjalan { get; set; }
        public Nullable<double> NilaiDalamMataUangAsal { get; set; }
        public string SebabMacet { get; set; }
        public string SebabMacetKet { get; set; }
        public Nullable<System.DateTime> TanggalMacet { get; set; }
        public Nullable<double> TunggakanPokok { get; set; }
        public Nullable<double> TunggakanBunga { get; set; }
        public Nullable<double> FrekuensiTunggakan { get; set; }
        public Nullable<double> Denda { get; set; }
        public Nullable<double> FrekuensiRestrukturisasi { get; set; }
        public Nullable<System.DateTime> TanggalRestrukturisasiAkhir { get; set; }
        public string KodeCaraRestrukturisasi { get; set; }
        public string RestrukturisasiKet { get; set; }
        public string Kondisi { get; set; }
        public string KondisiKet { get; set; }
        public Nullable<System.DateTime> TanggalKondisi { get; set; }
        public string Keterangan { get; set; }
    
        public virtual IdebFac IdebFac { get; set; }
    }
}
