//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthUserHist
    {
        public string UserId { get; set; }
        public int Seq { get; set; }
        public string TokenId { get; set; }
        public Nullable<System.DateTime> LogonTime { get; set; }
        public string LogonHost { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
    }
}
