//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdebFacBg
    {
        public string FacId { get; set; }
        public string Ljk { get; set; }
        public string LjkKet { get; set; }
        public string Cabang { get; set; }
        public string CabangKet { get; set; }
        public Nullable<double> NominalBg { get; set; }
        public Nullable<System.DateTime> TanggalDibentuk { get; set; }
        public Nullable<System.DateTime> TanggalUpdate { get; set; }
        public Nullable<int> Bulan { get; set; }
        public Nullable<int> Tahun { get; set; }
        public string NoRekening { get; set; }
        public string JenisGaransi { get; set; }
        public string JenisGaransiKet { get; set; }
        public Nullable<System.DateTime> TanggalDiterbitkan { get; set; }
        public Nullable<System.DateTime> TanggalJatuhTempo { get; set; }
        public string NoAkadAwal { get; set; }
        public Nullable<System.DateTime> TanggalAkadAwal { get; set; }
        public string NoAkadAkhir { get; set; }
        public Nullable<System.DateTime> TanggalAkadAkhir { get; set; }
        public string NamaYangDijamin { get; set; }
        public string Kolektibilitas { get; set; }
        public string Valuta { get; set; }
        public Nullable<double> Plafon { get; set; }
        public string TujuanGaransi { get; set; }
        public string TujuanGaransiKet { get; set; }
        public Nullable<double> SetoranJaminan { get; set; }
        public Nullable<System.DateTime> TanggalWanPrestasi { get; set; }
        public string Kondisi { get; set; }
        public string KondisiKet { get; set; }
        public Nullable<System.DateTime> TanggalKondisi { get; set; }
        public string Keterangan { get; set; }
    }
}
