//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdebCorpSearchVar
    {
        public string IdebId { get; set; }
        public string NamaBadanUsaha { get; set; }
        public string Npwp { get; set; }
        public string TempatPendirian { get; set; }
        public Nullable<System.DateTime> TanggalAktaPendirian { get; set; }
        public string NomorAktaPendirian { get; set; }
    
        public virtual Ideb Ideb { get; set; }
    }
}
