//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSupp
    {
        public string AppId { get; set; }
        public int Seq { get; set; }
        public string NameAsIDCard { get; set; }
        public string IDNumber { get; set; }
        public string NameOnCard { get; set; }
        public string Relationship { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string MothersMaidenName { get; set; }
        public string MobilePhoneNo { get; set; }
        public string Email { get; set; }
        public string NationalityCd { get; set; }
        public string CountryCd { get; set; }
    }
}
