//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataImport
    {
        public int ImportId { get; set; }
        public string ImportName { get; set; }
        public Nullable<int> OrderSeq { get; set; }
        public string SourceType { get; set; }
        public string DestTable { get; set; }
        public string Method { get; set; }
        public Nullable<bool> RowOverwrite { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
