//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIST
    {
        public string LISTID { get; set; }
        public string KEYFIELD { get; set; }
        public string KEYFIELDDESC { get; set; }
        public string LISTDESC { get; set; }
        public string LISTFIELD { get; set; }
        public string LISTFILTER { get; set; }
        public string LISTDETAIL { get; set; }
        public string LISTSQLPARAM { get; set; }
        public string LISTSQLCOND { get; set; }
        public string LISTGROUPBY { get; set; }
        public Nullable<bool> ALLOWSELECTION { get; set; }
        public Nullable<bool> ALLOWFILTER { get; set; }
        public Nullable<bool> ALLOWSORT { get; set; }
        public Nullable<bool> ALLOWGROUPBY { get; set; }
        public Nullable<bool> ALLOWEXPORT { get; set; }
        public string LISTDETAILDESC { get; set; }
        public string LISTDETAIL2 { get; set; }
        public string LISTDETAIL2DESC { get; set; }
        public string LISTCHKBOXCMD { get; set; }
        public string LISTCHKCMDTEXT { get; set; }
        public string LISTREASONQRY { get; set; }
        public string LISTREASONCAPTION { get; set; }
        public Nullable<bool> LISTREASONPOSFRONT { get; set; }
        public string LISTORDERBY { get; set; }
    }
}
