//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBS.Library.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ideb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ideb()
        {
            this.IdebCorpDatas = new HashSet<IdebCorpData>();
            this.IdebCorpGroups = new HashSet<IdebCorpGroup>();
            this.IdebFacs = new HashSet<IdebFac>();
            this.IdebIndivDatas = new HashSet<IdebIndivData>();
        }
    
        public string IdebId { get; set; }
        public string ReqId { get; set; }
        public Nullable<long> Seq { get; set; }
        public string DebtectorId { get; set; }
        public string KodeReferensiPengguna { get; set; }
        public Nullable<System.DateTime> TanggalHasil { get; set; }
        public string IdPermintaan { get; set; }
        public string IdPenggunaPermintaan { get; set; }
        public string DibuatOleh { get; set; }
        public string KodeLJKPermintaan { get; set; }
        public string KodeCabangPermintaan { get; set; }
        public string KodeTujuanPermintaan { get; set; }
        public Nullable<System.DateTime> TanggalPermintaan { get; set; }
        public Nullable<int> TotalBagian { get; set; }
        public string NomorBagian { get; set; }
        public string DebType { get; set; }
        public string NomorLaporan { get; set; }
        public string PosisiDataTerakhir { get; set; }
        public Nullable<System.DateTime> PosisiDataTerakhirDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdebCorpData> IdebCorpDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdebCorpGroup> IdebCorpGroups { get; set; }
        public virtual IdebCorpSearchVar IdebCorpSearchVar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdebFac> IdebFacs { get; set; }
        public virtual IdebFacSummary IdebFacSummary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdebIndivData> IdebIndivDatas { get; set; }
        public virtual IdebIndivSearchVar IdebIndivSearchVar { get; set; }
    }
}
